// Generated by CoffeeScript 1.6.2
(function() {
  var c, events, l, m, p, s,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  events = require('events');

  s = require('./storage');

  l = require('./location');

  p = require('./printer');

  c = require('./commands');

  m = require('./movement');

  exports.App = (function(_super) {
    __extends(App, _super);

    function App() {
      this.storage = new s.Storage(this);
      this.location = new l.Location(this);
      this.printer = new p.Printer(this);
      this.commands = new c.Commands(this);
      this.movement = new m.Movement(this);
      this.emit('print', 'Welcome to the abyss, a text adventure game type help for a list of commands.');
      this.emit('establishUser');
    }

    return App;

  })(events.EventEmitter);

}).call(this);
