// Generated by CoffeeScript 1.6.2
(function() {
  var http,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  http = require('http');

  exports.Location = (function() {
    function Location(app) {
      this.app = app;
      this.get = __bind(this.get, this);
      this.app.on('getLocation', this.get);
    }

    Location.prototype.get = function(options) {
      var url;
      url = "http://the-abyss.herokuapp.com/plots/fetch.json?x=" + options.x + "&y=" + options.y;
      console.log(url);
      return http.get(url, function(res) {
        var data;
        data = '';
        res.on('data', function(chunk) {
          return data += chunk;
        });
        return res.on('end', function() {
          return options.fn(JSON.parse(data));
        });
      }).on('error', function(e) {
        return console.log("Got error: ", e);
      });
    };

    return Location;

  })();

}).call(this);
